baseURL = "https://myblog.vercel.app/" # ä¸Šçº¿åä¼šè‡ªåŠ¨æ›¿æ¢
languageCode = "zh-cn"
title = "æˆ‘çš„ AI åšå®¢"
theme = "PaperMod"

[params]
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowShareButtons = true

[menu]
    [[menu.main]]
        identifier = "search"
        name = "ğŸ” æœç´¢"
        url = "/search/"
        weight = 10